version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  node_pytube:
    image: tjunyamasaki/node_pytube
    container_name: node_pytube
    ports:
      - 3000:3000